name: main

on:
  push:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  run-workflow:
    runs-on: self-hosted

    steps:
    - name: print something
      run: |
        echo "workflow running..."
  
